# Etapa de inicialização do PostgreSQL
FROM postgres:15-bullseye

ARG JDK_LOCALIZACAO
ARG APP_LOCALIZACAO
ARG POSTGRES_DB
ARG POSTGRES_USER
ARG POSTGRES_PASSWORD

# Variáveis de ambiente usadas pela imagem do PostgreSQL
ENV POSTGRES_DB=$POSTGRES_DB
ENV POSTGRES_USER=$POSTGRES_USER
ENV POSTGRES_PASSWORD=$POSTGRES_PASSWORD

# Criar diretório e copiar scripts de inicialização do banco de dados
RUN mkdir -p /docker-entrypoint-initdb.d
WORKDIR /docker-entrypoint-initdb.d
COPY scripts .

# Criar diretório para a aplicação e a JDK
RUN mkdir -p /app
RUN mkdir -p /app/jdk
WORKDIR /app

# Copiar o JAR da aplicação para o diretório atual
COPY ${APP_LOCALIZACAO} .

# Copiar a JDK para o diretório atual
COPY ${JDK_LOCALIZACAO} /app/jdk
RUN chmod +x /app/jdk/bin/*