spring:     
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test
    username: admin
    password: admin
    
  h2:
    console:
      enabled: true
      path: /h2-console
      
  sql:
    init:
      mode: always
      data-locations:
      - classpath:data.sql 
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    show-sql: true
    