spring:
  profiles:
    active: "prod"
  application: 
    name: service-system

server:
    port: 8080
    servlet:
      context-path: /api

springdoc:
  api-docs:
    path: /docs
  swagger-ui:
    path: /swagger.html
    operationsSorter: method

freeimage-upload-key: 6d207e02198a847aa98d0a2a901485a5

security:
  token:
    secret: service-system12345
    time: 1440
  refreshToken:
    time: 10080